### ISSUE TITLE
Bower issue

### ISSUE THREAD

**Issue by brunowego** [t0m/select2-bootstrap-css#72] opened 2015-03-25 18:14 UTC
When downloading using bower, this install creates a subfolder like:

```
bower_components/select2-bootstrap-css-1.4.6/
```

**Comment by fk** [comment] 2015-03-30 15:48
Hi Bruno, thanks for speaking up!

I just tried to reproduce the issue you described, however running `bower install select2-bootstrap-css` results in version 1.4.6 (from the [bootstrap3](https://github.com/t0m/select2-bootstrap-css/tree/bootstrap3) branch) being installed in `bower_components/select2-bootstrap-css/` for me (using Bower 1.3.12 and NPM 2.7.4 – the lastest stable releases).

I've been using Bower a lot during the last years, and I can't remember seeing the version number added to the folder name once – or reading about the latter. Could you describe your process? How did you come up with the fix you issued the pull request for?

**Comment by brunowego** [comment] 2015-03-30 17:50
Yes @fk. See below the issue:

![bug](https://cloud.githubusercontent.com/assets/441774/6902731/f6e19f34-d6eb-11e4-9686-9065196e5396.gif)

**Comment by fk** [comment] 2015-04-01 03:19
Wow! :weary:

> How did you come up with the fix you issued the pull request for?

I'd love to understand this.
Also, I've googled this quite a bit and couldn't find anything similar.

**Comment by ryanbeymer** [comment] 2015-04-01 03:32
Which ver. of bower? 

Here's my output, unable to duplicate as well, i'm on bower 1.4.0

```
bower not-cached    git://github.com/t0m/select2-bootstrap-css.git#*
bower resolve       git://github.com/t0m/select2-bootstrap-css.git#*
bower download      https://github.com/t0m/select2-bootstrap-css/archive/v1.4.6.tar.gz
bower extract       select2-bootstrap-css#* archive.tar.gz
bower resolved      git://github.com/t0m/select2-bootstrap-css.git#1.4.6
bower cached        git://github.com/ivaynberg/select2.git#3.4.8
bower validate      3.4.8 against git://github.com/ivaynberg/select2.git#^3.3.2
bower new           version for git://github.com/ivaynberg/select2.git#^3.3.2
bower resolve       git://github.com/ivaynberg/select2.git#^3.3.2
bower download      https://github.com/ivaynberg/select2/archive/3.5.2.tar.gz
bower extract       select2#^3.3.2 archive.tar.gz
bower resolved      git://github.com/ivaynberg/select2.git#3.5.2
bower cached        git://github.com/jquery/jquery.git#2.1.1
bower validate      2.1.1 against git://github.com/jquery/jquery.git#>= 1.7.1
bower new           version for git://github.com/jquery/jquery.git#>= 1.7.1
bower resolve       git://github.com/jquery/jquery.git#>= 1.7.1
bower download      https://github.com/jquery/jquery/archive/2.1.3.tar.gz
bower extract       jquery#>= 1.7.1 archive.tar.gz
bower resolved      git://github.com/jquery/jquery.git#2.1.3
bower install       select2-bootstrap-css#1.4.6
bower install       select2#3.5.2
bower install       jquery#2.1.3
```

**Comment by fk** [comment] 2015-04-01 12:23
Thanks for chiming in @ryanbeymer. It's Bower v1.3.12 for me (no problems, output similar to what you pasted) as well as for @brunowego. I also updated to Bower v1.4.0 yesterday, same (positive) result for me with v1.4.1 today.

**Comment by ryanbeymer** [comment] 2015-04-01 15:21
Doesn't appear to be repo related, looks like func. of bower. 

http://stackoverflow.com/a/21777649/1119965

**Comment by ryanbeymer** [comment] 2015-04-08 00:46
@fk i think you could close this now

**Closed** 2015-04-08 00:48 UTC

**Comment by fk** [comment] 2015-04-08 00:52
Thanks guys!

@brunowego – does this work for you now?
