### ISSUE TITLE
Stop scrolling when you reach the bottom of the select2 list

### ISSUE THREAD

**Issue by vincentjames501** [t0m/select2-bootstrap-css#94] opened 2015-11-12 17:02 UTC
To reproduce.

Take any select2 from [here](http://select2.github.io/select2/), open the selection, and quickly scroll to the bottom. Notice the body does not move.

Now take any select2 from [here](https://fk.github.io/select2-bootstrap-css/), open the selection, and quickly scroll to the bottom. Notice the entire page moves.

I think this should be consistent with how native select fields work in the browser (don't scroll the parent's body)

**Comment by xpundel** [comment] 2016-05-04 15:38
If you'll use a select2.full.js the behaviour will be correct. I didn't dig into it, but I think one of the plugins bundled in the full package is preventing page scroll.

**Comment by Laykou** [comment] 2017-07-28 09:53
I have also a requirement to fix this behavior - not to scroll the page, when bottom of select2 is reached. Can someone confirm that the issue is resolved (or put related commit/PR)? Can this issue be closed? 

What version should be used? ANd if it is not fixed when it could be? Thank you very much

**Comment by fk** [comment] 2017-07-28 23:24
Hi @Laykou!

This project – __select2-bootstrap-css__ – provided CSS to integrate Select2 __v3__ with Bootstrap 2 and 3. For Select2 __v4__ it is continued as an official theme as [__select2-bootstrap-theme__]( https://select2.github.io/select2-bootstrap-theme/) (and only targets integration with Bootstrap 3). _Please consider upgrading to Select2 __v4__ if you can!

---

The __full build of Select2 v4__ – `select2.full.js` – which @xpundel mentioned earlier in this thread, contains _"additional features and recommended includes"_:

![image](https://user-images.githubusercontent.com/21834/28739350-9bbef134-73fa-11e7-9d03-b712b089c165.png)

As you can see above in the screenshot from the current [v4 documentation for Select2](https://select2.github.io/), among those "recommended includes" is `jquery.mousewheel.js`. This additional jQuery plugin is what you need to manually include along with Select2 __v3__ to fix your issue. Quoting the Select2 v3.5.3 source code:

> if jquery.mousewheel plugin is installed we can prevent out-of-bounds scrolling of results via mousewheel

Here's a link to the version of jquery.mousewheel.js that makes things work on the [Select2 v3.5.3](https://select2.github.io/select2/) demonstation/documentation page: https://select2.github.io/select2/js/jquery.mousewheel.js

---

I hope this helps!
Closing this as it is not at all an issue of select2-bootstrap-css. ✌️

**Closed by fk** 2017-07-28 23:24 UTC
